config/routes.rb
CatsInc::Application.routes.draw do

  resources :purchases, only: [:create, :show]

  resources :items, only: [:index]

  root 'items#index'
end

app/models/item.rb
class Item < ActiveRecord::Base

  scope :in_stock, ->{ where("stock > 0")}

  has_many :purchases

  def reduce_stock!
    self.stock -= 1
    save!
  end
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base

  belongs_to :item

  after_save :reduce_stock_of_item

  def reduce_stock_of_item
    self.item.reduce_stock!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  # GET /items
  # GET /items.json
  def index
    @items = Item.in_stock
  end

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  def show
    @purchase = Purchase.find(params[:id])
  end

  def create
    @purchase = Purchase.new(purchase_params)

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to @purchase, notice: 'Thank you for your purchase!' }
        format.json { render action: 'show', status: :created, location: @purchase }
      else
        format.html { render action: 'new' }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def purchase_params
      params.require(:purchase).permit(:item_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper

  def format_as_price(price_in_pence)
    pounds = price_in_pence / 100.0
    number_to_currency pounds, unit: "£", precision: 2
  end
end

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Price</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.image %></td>
        <td class="price"><%= format_as_price item.price %></td>
        <td>In stock: <%= item.stock %></td>
        <td><%= button_to 'Buy', purchases_path(purchase: {item_id: item.id}) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CatsInc</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/purchases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @purchase.item_id %>
</p>